// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _13_Sacrament_Planning.Models;

namespace _13_Sacrament_Planning.Migrations
{
    [DbContext(typeof(SacramentPlanningContext))]
    partial class SacramentPlanningContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_13_Sacrament_Planning.Models.Hymn", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Hymn");
                });

            modelBuilder.Entity("_13_Sacrament_Planning.Models.Meeting", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("BishopricRole");

                    b.Property<string>("ClosingHymn");

                    b.Property<string>("ClosingPrayerMember");

                    b.Property<DateTime>("Date");

                    b.Property<string>("OpeningHymnID");

                    b.Property<string>("OpeningPrayerMember");

                    b.Property<string>("SacramentHymn");

                    b.HasKey("ID");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("_13_Sacrament_Planning.Models.Member", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("_13_Sacrament_Planning.Models.Speaker", b =>
                {
                    b.Property<int>("MemberID");

                    b.Property<int>("MeetingID");

                    b.Property<string>("Topic");

                    b.HasKey("MemberID", "MeetingID");

                    b.HasIndex("MeetingID");

                    b.ToTable("Speaker");
                });

            modelBuilder.Entity("_13_Sacrament_Planning.Models.Speaker", b =>
                {
                    b.HasOne("_13_Sacrament_Planning.Models.Meeting", "Meeting")
                        .WithMany("Speakers")
                        .HasForeignKey("MeetingID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("_13_Sacrament_Planning.Models.Member", "Member")
                        .WithMany("Talks")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
